In [34]:
import pandas as pd
import numpy as np

In [40]:
class test:
    def __init__(self, a, b):
        self.a = a
        self.b = b
        
    def values(self):
        self.name = "name_test"

test.values(test)
print(test.name)


name_test


In [ ]:
a = 1
print(f"테테테테{a}테테테")

테테테테1테테테


In [54]:
class point:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __repr__(self):
        return f"Point(x={self.x}, y={self.y})"
    
# repr(point(2, 3))

print(repr("text"))


'text'


In [ ]:
iter_01 = iter(range(0, 10))
print(iter_01)
print(next(iter_01))
print(next(iter_01))
print(next(iter_01))
print(next(iter_01))

0
1
2
3


In [23]:
def deco(func):
    print("hi")
    func
    print("end")

def gen():
    a = 1
    yield a
    a += 1
    print(a)


next(gen())

1

In [33]:
[x * x for x in range(10)]


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [105]:
arr_01 = np.array([[1, 2, 3],
                  [4, 5, 6]])

arr_02 = np.array([[1, 2, 3],
                  [4, 4, 4]])


In [106]:
print(arr_01[1:2]+1 )
print(arr_01[1][1])

[[5 6 7]]
5


In [109]:
re_01 = arr_01.reshape(6, 1)

print(re_01.shape)
print(np.transpose(re_01).shape)
print(re_01.flatten().shape)
print(re_01.ravel().shape)

(6, 1)
(1, 6)
(6,)
(6,)


In [103]:
print(arr_01 + arr_02)


[[ 2  4  6]
 [ 8  9 10]]


In [94]:
a = np.zeros(arr_01.shape)
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [110]:
a = np.split(arr_01, 1)
print(a)

[array([[1, 2, 3],
       [4, 5, 6]])]


In [116]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"
df = pd.read_csv(url)
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [120]:
df.describe

<bound method NDFrame.describe of      PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                 

In [125]:
df["Name"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...                        
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [128]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [143]:
filter_1 = df[df['Age'] < 25]
print(filter_1)

     PassengerId  Survived  Pclass                                 Name  \
0              1         0       3              Braund, Mr. Owen Harris   
7              8         0       3       Palsson, Master. Gosta Leonard   
9             10         1       2  Nasser, Mrs. Nicholas (Adele Achem)   
10            11         1       3      Sandstrom, Miss. Marguerite Rut   
12            13         0       3       Saundercock, Mr. William Henry   
..           ...       ...     ...                                  ...   
875          876         1       3     Najib, Miss. Adele Kiamie "Jane"   
876          877         0       3        Gustafsson, Mr. Alfred Ossian   
877          878         0       3                 Petroff, Mr. Nedelio   
882          883         0       3         Dahlberg, Miss. Gerda Ulrika   
887          888         1       1         Graham, Miss. Margaret Edith   

        Sex   Age  SibSp  Parch     Ticket     Fare Cabin Embarked  
0      male  22.0      1      